import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('dem.sal.csv')
Oldest = df['age'].max()
Youngest = df['age'].min()
Department_count = df['Department'].value_counts()
oldest_highest_salary = df[df['age'] == Oldest]['salary'].max()
oldest_lowest_salary = df[df['age'] == Oldest]['salary'].min()
youngest_highest_salary = df[df['age'] == Youngest]['salary'].max()
youngest_lowest_salary = df[df['age'] == Youngest]['salary'].min()
total_salary_department = df.groupby('Department')['salary'].sum()

print ("The oldest employee is:")
print (Oldest)
print ("The youngest employee is:")
print (Youngest)
print ("The number of employees in each department is:")
print (Department_count)
print ("The highest salary of the oldest employee is:")
print (oldest_highest_salary)
print ("The lowest salary of the oldest employee is:")
print (oldest_lowest_salary)
print ("The highest salary of the youngest employee is:")
print (youngest_highest_salary)
print ("The lowest salary of the youngest employee is:")
print (youngest_lowest_salary)
print ("The total salary of each department is:")
print (total_salary_department)
plt.figure(figsize=(10, 6))
sns.barplot(x=total_salary_department.index, y=total_salary_department.values)
plt.title('Total Salary by Department')
plt.xlabel('Department',fontsize=10)
plt.ylabel('Total Salary',fontsize=12)
plt.tight_layout()
plt.savefig('screenshots/total_salary_by_department.png')
plt.yticks(range(0, 90001, 10000))
plt.show()